---
title: "Pollution Plot"
author: "Darren Shoemaker"
format: html
toc: true
embed-resources: true
editor: visual
---

## Libraries

```{r}
#| output: false
library(ggplot2)
library(maps)
library(sf)
library(mapproj)
library(ggspatial)
library(tidyverse)
library(here)
```

## Read Data and Data Cleaning

```{r}
#| output: false
dat <- read.csv(here('data/raw', 'res_pollution_v4.csv')) %>% 
  mutate(Poll_clus = factor(Poll_clus))
state <- map_data('state')
sites <- st_as_sf(dat, coords = c('Latitude', 'Longitude'),
                  crs = 3174, agr = 'constant')

# Data Cleaning

str(dat)
summary(dat)
```

## Pollution Plot

```{r}
#| warning: false
cluster_map <- ggplot() +
  geom_polygon(
    data = state,
    aes(x = long, y = lat, group = group),
    fill = 'white',
    color = 'black'
  ) +
  geom_point(dat = dat, aes(x = Longitude, y = Latitude), shape = 19, size = 1, color = 'black') +
  coord_map('albers', lat0 = 39, lat1 = 45) +
  labs(x = 'Longitude', y = 'Latitude') +
  theme(legend.title = element_blank(),
        text = element_text(family = 'Times New Roman'))
cluster_map
```

## Export Figure

```{r}
ggsave(filename = here('output', '1_pollution_cluster_map.png'), plot = cluster_map, dpi = 1200)
```
